package com.nekyia.bountyfulSeas.nexo;

import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.InvalidConfigurationException;
import org.bukkit.configuration.file.YamlConfiguration;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.OptionalDouble;
import java.util.Set;
import java.util.stream.Stream;

/**
 * Writes a Nexo item definition for every {@link NexoItem} that lacks one.
 *
 * <p>Nexo has no API for creating items at runtime: {@code NexoItems} only reads,
 * and items are built from the YAML in its own {@code items} folder while the
 * resource pack is generated. So the blueprint is written to disk before Nexo
 * enables, and Nexo picks it up as if it had always been there.
 *
 * <p>Fields split into two kinds, and the split is the whole contract:
 * <ul>
 *   <li><b>Derived</b> - {@code itemname}, {@code lore} and the food components come
 *       from the {@link NexoItem}, so they are rewritten on every run and cannot go
 *       stale when the item behind them is renamed or recategorised.</li>
 *   <li><b>Hand held</b> - {@code material}, {@code Pack} and {@code Mechanics} are
 *       written once when the stub is created and never touched again, which is what
 *       makes it safe to swap a texture or model and keep it across restarts.</li>
 * </ul>
 *
 * <p>An id that already exists in some other Nexo item file is left alone entirely.
 */
public final class NexoBlueprintWriter {

    /** Written below Nexo's own items folder so it never collides with hand made files. */
    public static final String TARGET = "bountyfulseas/fish.yml";

    private static final int MODEL_DATA_BASE = 9000;

    /**
     * Paper carries no food component, so an item is inedible unless it asks for
     * one. A vanilla food material such as COD would arrive edible on its own and
     * quietly contradict an item that declares no saturation.
     */
    private static final String DEFAULT_MATERIAL = "PAPER";

    private static final String DEFAULT_PARENT_MODEL = "item/generated";
    private static final String TEXTURE_FOLDER = "bountyfulseas/";

    private static final String COMPONENTS = "Components";
    private static final String FOOD = "food";
    private static final String CONSUMABLE = "consumable";

    /**
     * Roughly how long vanilla takes to eat.
     *
     * <p>Written in Nexo's own canonical form. Nexo rewrites item files it has read,
     * normalising {@code consume_seconds: 1.6} to {@code consume_duration: 1.6s}, so
     * writing anything else here would differ from the file on every startup and the
     * two of us would rewrite it back and forth forever.
     */
    private static final String CONSUME_DURATION = "1.6s";

    private static final List<String> HEADER = List.of(
            "Generated by BountyfulSeas - do not delete, but do edit.",
            "",
            "material, Pack and Mechanics are yours: written once, never touched again,",
            "so swapping a texture or model here survives restarts.",
            "",
            "itemname, lore and the food components are derived from the fish definition",
            "and are rewritten every start, so editing those here will not stick.",
            "",
            "Deleting an entry regenerates it from scratch.");

    private NexoBlueprintWriter() {
    }

    /**
     * @param nexoFolder Nexo's plugin data folder, normally {@code plugins/Nexo}
     * @param items      the items to make sure Nexo has
     */
    public static BlueprintResult write(Path nexoFolder, Collection<? extends NexoItem> items) {
        Path itemsFolder = nexoFolder.resolve("items");
        if (!Files.isDirectory(itemsFolder)) {
            return BlueprintResult.skipped("Nexo items folder not found at " + itemsFolder);
        }

        Path target = itemsFolder.resolve(TARGET);

        YamlConfiguration blueprint = new YamlConfiguration();
        if (Files.isRegularFile(target)) {
            try {
                blueprint.load(target.toFile());
            } catch (IOException | InvalidConfigurationException exception) {
                return BlueprintResult.skipped(TARGET + " could not be read, leaving it untouched: "
                        + exception.getMessage());
            }
        }

        Set<String> takenIds = new HashSet<>();
        Set<Integer> takenModelData = new HashSet<>();
        scanExisting(itemsFolder, target, takenIds, takenModelData);

        List<String> created = new ArrayList<>();
        boolean changed = false;
        int modelData = MODEL_DATA_BASE;

        for (NexoItem item : items) {
            String id = item.id();

            ConfigurationSection section = blueprint.getConfigurationSection(id);
            if (section == null) {
                // Someone else already defines this id, so it is not ours to write.
                if (takenIds.contains(id)) {
                    continue;
                }

                while (takenModelData.contains(modelData)) {
                    modelData++;
                }

                section = blueprint.createSection(id);
                section.set("material", DEFAULT_MATERIAL);

                ConfigurationSection pack = section.createSection("Pack");
                pack.set("parent_model", DEFAULT_PARENT_MODEL);
                pack.set("custom_model_data", modelData);
                pack.set("texture", TEXTURE_FOLDER + id + ".png");

                section.createSection("Mechanics").createSection("misc")
                        .set("allow_in_vanilla_recipes", false);

                takenIds.add(id);
                takenModelData.add(modelData);
                created.add(id);
                changed = true;
            }

            changed |= applyDerived(section, item);
        }

        if (!changed) {
            return BlueprintResult.unchanged(target);
        }

        blueprint.options().setHeader(HEADER);
        try {
            Files.createDirectories(target.getParent());
            blueprint.save(target.toFile());
        } catch (IOException exception) {
            return BlueprintResult.skipped("could not write " + TARGET + ": " + exception.getMessage());
        }

        return BlueprintResult.written(target, created);
    }

    /**
     * Rewrites everything the {@link NexoItem} determines, and reports whether any
     * of it actually moved.
     */
    private static boolean applyDerived(ConfigurationSection section, NexoItem item) {
        boolean changed = setValue(section, "itemname", item.displayName());
        changed |= setValue(section, "lore", List.copyOf(item.lore()));
        changed |= applyFood(section, item);
        return changed;
    }

    /**
     * An item is edible only while it declares saturation. When that goes away the
     * components come back off, so the item follows its source in both directions.
     */
    private static boolean applyFood(ConfigurationSection section, NexoItem item) {
        ConfigurationSection components = section.getConfigurationSection(COMPONENTS);

        OptionalDouble saturation = item.foodSaturation();

        if (saturation.isEmpty()) {
            if (components == null) {
                return false;
            }
            boolean changed = remove(components, FOOD) | remove(components, CONSUMABLE);
            if (changed && components.getKeys(false).isEmpty()) {
                section.set(COMPONENTS, null);
            }
            return changed;
        }

        if (components == null) {
            components = section.createSection(COMPONENTS);
        }

        Map<String, Object> food = new LinkedHashMap<>();
        food.put("nutrition", 0);
        food.put("saturation", saturation.getAsDouble());
        food.put("can_always_eat", false);

        Map<String, Object> consumable = new LinkedHashMap<>();
        consumable.put("consume_duration", CONSUME_DURATION);

        return setSection(components, FOOD, food) | setSection(components, CONSUMABLE, consumable);
    }

    private static boolean remove(ConfigurationSection section, String key) {
        if (!section.contains(key)) {
            return false;
        }
        section.set(key, null);
        return true;
    }

    private static boolean setValue(ConfigurationSection section, String key, Object value) {
        if (value.equals(section.get(key))) {
            return false;
        }
        section.set(key, value);
        return true;
    }

    private static boolean setSection(ConfigurationSection parent, String key, Map<String, Object> desired) {
        ConfigurationSection existing = parent.getConfigurationSection(key);
        if (existing != null && existing.getValues(false).equals(desired)) {
            return false;
        }
        parent.set(key, null);
        ConfigurationSection section = parent.createSection(key);
        desired.forEach(section::set);
        return true;
    }

    /**
     * Collects every item id and every custom model data value Nexo already knows,
     * so a generated stub never shadows a hand made item or steals its model data.
     *
     * <p>The generated file counts for model data but not for ids. Its ids are ours
     * to rewrite, so treating them as taken would stop us updating our own entries -
     * but its model data is every bit as spoken for as anybody else's, and skipping
     * it made allocation start from the base again on every run and hand a new entry
     * a number one of our own already had.
     */
    private static void scanExisting(Path itemsFolder, Path target, Set<String> ids, Set<Integer> modelData) {
        try (Stream<Path> paths = Files.walk(itemsFolder)) {
            for (Path file : paths.filter(Files::isRegularFile).filter(NexoBlueprintWriter::isYaml).toList()) {
                boolean ours = file.equals(target);
                YamlConfiguration yaml = new YamlConfiguration();
                try {
                    yaml.load(file.toFile());
                } catch (IOException | InvalidConfigurationException exception) {
                    // A file Nexo cannot read either is not ours to report on.
                    continue;
                }
                for (String id : yaml.getKeys(false)) {
                    if (!ours) {
                        ids.add(id);
                    }
                    ConfigurationSection section = yaml.getConfigurationSection(id);
                    if (section == null) {
                        continue;
                    }
                    ConfigurationSection pack = section.getConfigurationSection("Pack");
                    if (pack != null && pack.get("custom_model_data") instanceof Number value) {
                        modelData.add(value.intValue());
                    }
                }
            }
        } catch (IOException exception) {
            // Nothing scanned means nothing claimed; allocation starts from the base.
        }
    }

    private static boolean isYaml(Path path) {
        String name = path.getFileName().toString().toLowerCase(Locale.ROOT);
        return name.endsWith(".yml") || name.endsWith(".yaml");
    }
}
